# Generated by Django 3.0.7 on 2020-07-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200704_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.CharField(default=True, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='placer',
            field=models.CharField(default=True, max_length=64),
            preserve_default=False,
        ),
    ]
