# Generated by Django 3.0.7 on 2020-07-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200704_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=False, max_length=600),
            preserve_default=False,
        ),
    ]
