# Generated by Django 3.0.7 on 2020-07-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
