# Generated by Django 3.0.7 on 2020-07-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
